work_dir: '/home/mka3dlab/Documents/logs/mandibles'
version: 16
seed: 0

model:
  channels_list: [16, 32, 64, 128]
  lr: 0.01
  epochs: 500
  warmup_epochs: 20
  weight_decay: 0
  num_awms: 3

datamodule:
  root: '/mnt/diag/nielsvannistelrooij/Fabian'
  # root: '/home/mka3dlab/Documents/fractures'
  regex_filter: ''
  val_size: 0.2
  batch_size: 2
  num_workers: 1
  pin_memory: True
  persistent_workers: True
  regular_spacing: 0.5  # mm
  patch_size: 64
  stride: 48
  max_patches_per_scan: 4
