work_dir: '/home/mka3dlab/Documents/logs/semseg'
version: 5
seed: 0

model:
  channels_list: [48, 96, 192, 256, 256]
  depths: [3, 9, 3, 3]
  heads_list: [6, 12, 24, 24]
  window_sizes: [0.2, 0.4, 0.8, 1.6]
  point_embedding:
    use: True
    kpconv_point_influence: 0.02
    kpconv_ball_radius: 0.05
  stratified_union: False
  downsample_ratio: 0.26
  max_drop_path_prob: 0.3
  stratified_downsample_ratio: 0.26
  crpe_bins: 80
  lr: 0.0006
  transformer_lr_ratio: 0.1
  weight_decay: 0.05
  epochs: 100
  warmup_epochs: 5
  prob_threshold: 0.9

datamodule:
  root: '/mnt/diag/nielsvannistelrooij/Fabian_clean'
  # root: '/mnt/diag/nielsvannistelrooij/Fabian_split'
  # root: '/home/mka3dlab/Documents/fractures/jawfrac'
  regex_filter: ''
  val_size: 0.2
  batch_size: 1
  num_workers: 1
  pin_memory: False
  persistent_workers: True
  foreground_hu_threshold: 500
  downsample_voxel_size: 0.04
  downsample_max_points: 100_000
