work_dir: '/home/mkaailab/Documents/logs/fracnet'
version: 2
seed: 0

model:
  lr: 0.1
  epochs: 100
  warmup_epochs: 1
  weight_decay: 0.0  
  num_awms: 0
  coords: ''
  backbone: 'conv'
  channels_list: [16, 32, 64, 128]
  head_kernel_size: 1
  cascade: False
  focal_loss: False
  dice_loss: True
  conf_threshold: 0.1
  min_component_size: 200

datamodule:
  root: '/mnt/diag/fractures'
  regex_filter: 'Annotation UK'
  val_size: 0.2
  test_size: 0.2
  batch_size: 4
  num_workers: 1
  pin_memory: True
  persistent_workers: True
  regular_spacing: 0.4  # mm
  patch_size: 64
  stride: 48
  expand_label:
    bone_iters: 0
    all_iters: 0
    smooth: 0.0
    negative_iters: 16
  max_patches_per_scan: 4

accumulate_grad_batches: 1
