work_dir: '/home/mka3dlab/Documents/logs/fractures'
version: 33
seed: 0

model:
  channels_list: [16, 32, 64, 128]
  lr: 0.01
  epochs: 500
  warmup_epochs: 20
  weight_decay: 0.0
  num_awms: 0
  backbone: 'conv'
  first_stage:
    checkpoint_path: 'checkpoints/mandibles_positions_size=0.4.ckpt'
    return_features: False
    head_kernel_size: 3
  second_stage:
    coords: ''
    checkpoint_path: ''  # 'checkpoints/fractures_linear2.ckpt'
  focal_loss: True
  dice_loss: False
  conf_threshold: 0.2
  min_component_size: 2048

datamodule:
  root: '/home/mka3dlab/Documents/fractures'
  # root: '/mnt/diag/nielsvannistelrooij/fractures'
  regex_filter: 'Annotation UK'
  linear: True
  displacements: True
  val_size: 0.2
  test_size: 0.2
  batch_size: 4
  num_workers: 1
  pin_memory: True
  persistent_workers: True
  mandible_crop:
    padding: 10.0  # mm
    extend: True
  regular_spacing: 0.4  # mm
  patch_size: 64
  stride: 48
  expand_label:
    bone_iters: 1
    all_iters: 1
    smooth: 0.5
    negative_iters: 16
  gamma_adjust: False
  max_patches_per_scan: 4
  class_label_to_idx: [0, 1, 1]
  ignore_outside: False
