work_dir: '/mnt/d/nielsvannistelrooij/logs'
# work_dir: '/output'
version: 303
seed: 0

model:
  lr: 0.002
  epochs: 500
  warmup_epochs: 20
  weight_decay: 0.01
  first_stage:
    num_awms: 3
    backbone: 'conv'
    channels_list: [16, 32, 64, 128]
    checkpoint_path: ''
    head_kernel_size: 1
    return_features: True
  second_stage:
    num_awms: 0
    coords: ''
    backbone: 'conv'
    channels_list: [16, 32, 64, 128]
    head_kernel_size: 1
    return_features: False
    cascade: True
    checkpoint_path: ''
  third_stage:
    num_awms: 0
    dropout: False
    coords: ''
    backbone: 'conv'
    channels_list: [16, 32, 64, 128]
  x_axis_flip: True
  post_processing:
    max_dist: 12.5  # 5 mm
    linear_conf_threshold: 0.1
    linear_min_component_size: 3072
    displaced_conf_threshold: 0.95
    displaced_min_component_size: 32_000
    mean_conf_threshold: 0.5
    mean_min_component_size: 3072
    verbose: False

datamodule:
  root: '/mnt/d/nielsvannistelrooij/fractures'
  # root: '/input'
  # root: '/mnt/diag/nielsvannistelrooij/fractures'
  regex_filter: 'Annotation UK'
  val_size: 0.2
  test_size: 0.2
  batch_size: 24
  num_workers: 1
  pin_memory: True
  persistent_workers: True
  mandible_crop:
    padding: 10.0  # mm
    extend: True
  regular_spacing: 0.4  # mm
  haar_transform: False
  patch_size: 64
  stride: 24
  expand_label:
    bone_iters: 1
    all_iters: 1
    smooth: 0.5
    negative_iters: 16
  gamma_adjust: False
  max_patches_per_scan: 4
  class_label_to_idx: [0, 1, 1]
  ignore_outside: True

accumulate_grad_batches: 1
