work_dir: '/home/mka3dlab/Documents/logs/fractures'
version: dice_loss
seed: 0

model:
  channels_list: [16, 32, 64, 128]
  lr: 0.01
  epochs: 500
  warmup_epochs: 20
  weight_decay: 0.0
  num_awms: 0
  state_dict_path: ''  # 'checkpoints/unet.ckpt'
  focal_loss: False
  dice_loss: True
  conf_threshold: 0.2
  min_component_size: 2048

datamodule:
  root: '/home/mka3dlab/Documents/fractures'
  regex_filter: ''
  val_size: 0.2
  test_size: 0.0
  batch_size: 4
  num_workers: 1
  pin_memory: True
  persistent_workers: True
  mandible_crop_padding: 5  # mm
  regular_spacing: 0.4  # mm
  patch_size: 64
  stride: 48
  expand_label:
    bone_iters: 1
    all_iters: 1
  max_patches_per_scan: 4
