work_dir: '/home/mka3dlab/Documents/logs/mandibles'
version: 101
seed: 0

model:
  channels_list: [16, 32, 64, 128]
  lr: 0.005
  epochs: 500
  warmup_epochs: 20
  weight_decay: 0.01
  backbone: 'conv'
  num_awms: 3
  head_kernel_size: 1
  focal_loss: False
  dice_loss: False
  x_axis_flip: True
  distance_filter: True

datamodule:
  # root: '/mnt/diag/nielsvannistelrooij/Fabian'
  root: '/home/mka3dlab/Documents/fractures'
  regex_filter: 'Annotation UK/17/'
  val_size: 0.2
  test_size: 0.0
  batch_size: 40
  num_workers: 1
  pin_memory: True
  persistent_workers: True
  regular_spacing: 0.4  # mm
  patch_size: 64
  stride: 24
  gamma_adjust: True
  max_patches_per_scan: 4
  ignore_outside: False

accumulate_grad_batches: 1
