work_dir: '/home/mka3dlab/Documents/logs/patchseg'
version: 9
seed: 0

model:
  channels_list: [16, 32, 64, 128]
  lr: 0.01
  epochs: 500
  warmup_epochs: 20
  weight_decay: 0

datamodule:
  root: '/home/mka3dlab/Documents/fractures/jawfrac'
  regex_filter: ''
  val_size: 0.2
  batch_size: 1
  num_workers: 1
  pin_memory: True
  persistent_workers: True
  mandible_crop_padding: 5  # mm
  regular_spacing: 0.4  # mm
  patch_size: 64
  stride: 48
  bone_hu_threshold: 500
  bone_volume_threshold: 0.01
